baseURL = "docs/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "section.io Documentation"
theme = "docdock"
# themesdir = "../.."

[params]
editURL = "https://github.com/section-io/docs/blob/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/section-io/docs"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i> Community"
url = "https://community.section.io/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> section.io Home"
identifier = "hugodoc"
url = "https://www.section.io/"
weight = 20
